name: Android Debug APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-debug-apk:
    runs-on: ubuntu-22.04
    timeout-minutes: 50
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          python3-venv \
          libssl-dev \
          libffi-dev \
          libncurses5 libncurses5-dev libtinfo5

      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Cache .buildozer and .gradle
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.gradle
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Build debug APK
        run: buildozer android debug

      - name: List build outputs (debug)
        if: success()
        run: ls -R bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: allergy-database-debug-apk
          path: bin/*.apk
          if-no-files-found: error

      - name: Summarize build environment
        if: always()
        run: |
          echo 'Python version:' $(python --version)
          echo 'Java version:' $(java -version 2>&1 | head -n1)
          echo 'Disk usage:'
          df -h .
