name: Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip git zip unzip openjdk-11-jdk
      - name: Create venv and install buildozer
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install buildozer
      - name: Build APK (debug)
        run: |
          . venv/bin/activate
          buildozer android debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
