name: Build Release AAB

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip git zip unzip openjdk-11-jdk
      - name: Create venv and install buildozer
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install buildozer
      - name: Cache Android SDK/NDK and p4a
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.local/share/python-for-android
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
      - name: Decode keystore
        env:
          KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$KEYSTORE_B64" ]; then
            echo "$KEYSTORE_B64" | base64 --decode > release.keystore
          else
            echo "No keystore provided; aborting"; exit 1
          fi
      - name: Build release AAB
        env:
          ANDROID_KEYSTORE: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          . venv/bin/activate
          # Configure buildozer for signing (override values)
          buildozer --verbose android release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: bin/*.aab
